# VISX Configuration for Training Mode
mode: training
output_dir: outputs/training_example
save_checkpoints: true
verbose: true

dataset:
  name: cifar10
  num_classes: 10
  input_channels: 3
  train_split: train
  test_split: test
  image_key: image
  label_key: label
  num_epochs: 5
  eval_every: 200
  batch_size: 128

model:
  name: yat_cnn
  type: yat
  num_classes: 10
  input_channels: 3
  architecture_params: {}

training:
  learning_rate: 0.003
  momentum: 0.9
  optimizer: adamw
  rng_seed: 42
  precision: float32

pretraining:
  method: supervised
  temperature: 0.1
  projection_dim: 128
  momentum_tau: 0.996
  augmentation_strength: 0.5

explainability:
  enabled: false
  methods: [saliency, kernels]
  layer_names: [conv1, conv2]
  num_samples: 16

mesh:
  enabled: true
  auto_detect: true
  # Optional: Override automatic detection with custom mesh configuration
  # shape: [4, 2]  # Mesh shape for custom topology
  # axis_names: [batch, model]  # Axis names for custom topology
  # TPU-specific settings (used when auto_detect=false and backend=tpu)
  # tpu_mesh_shape: [4, 2]
  # tpu_axis_names: [batch, model]
  # GPU-specific settings (used when auto_detect=false and backend!=tpu)  
  # gpu_mesh_shape: [8, 1]
  # gpu_axis_names: [batch, model]